spring.application.name=e-commer

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/techshop?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update


